name: Pipeline

defaults:
  run:
    shell: bash

on:
  push:
    branches-ignore:
      - master

jobs:
  install-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install
        run: |
          python --version
          node --version
          npm --version

          npm install -g aws-cdk

          python -m pip install . --upgrade
          python -m pip list

      - name: Test
        run: cd b_twilio_sdk_layer_test && cdk synth && cd ..
