name: Pipeline

defaults:
  run:
    shell: bash

on:
  push:
    branches-ignore:
      - master

jobs:
  install-test:
    runs-on: ubuntu-latest
    container: biomapas/cicd-full:0.0.1

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          pip install . --upgrade
          pip list
